package com.fp3.haras.view.screens.products;

import com.fp3.haras.utils.Colors;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ProductsCreate extends javax.swing.JFrame {

    public ProductsCreate() {
        initComponents();
        lblTitle.putClientProperty("FlatLaf.styleClass", "h00");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();
        tpProducts = new javax.swing.JTabbedPane();
        pnlProductsCreate = new javax.swing.JPanel();
        lblProductName = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        lblProductStock = new javax.swing.JLabel();
        txtProductStock = new javax.swing.JTextField();
        lblUnit = new javax.swing.JLabel();
        lblPurchasePrice = new javax.swing.JLabel();
        txtPurchasePrice = new javax.swing.JTextField();
        lblUnit1 = new javax.swing.JLabel();
        lblSalePrice = new javax.swing.JLabel();
        txtSalePrice = new javax.swing.JTextField();
        lblUnit2 = new javax.swing.JLabel();
        btnCancelProduct = new javax.swing.JButton();
        btnSaveProduct = new javax.swing.JButton();
        pnlServicesCreate = new javax.swing.JPanel();
        lblServiceType = new javax.swing.JLabel();
        txtServiceType = new javax.swing.JTextField();
        lblServicePrice = new javax.swing.JLabel();
        txtServicePrice = new javax.swing.JTextField();
        lblUnit3 = new javax.swing.JLabel();
        btnCancelService = new javax.swing.JButton();
        btnSaveService = new javax.swing.JButton();
        pnlStableTypeCreate = new javax.swing.JPanel();
        lblStableType = new javax.swing.JLabel();
        txtStableType = new javax.swing.JTextField();
        lblStablePrice = new javax.swing.JLabel();
        txtStablePrice = new javax.swing.JTextField();
        lblUnit4 = new javax.swing.JLabel();
        btnCancelStable = new javax.swing.JButton();
        btnSaveStable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("CRIAÇÃO");

        lblProductName.setText("NOME DO PRODUTO");

        txtProductName.setMaximumSize(new java.awt.Dimension(64, 22));

        lblProductStock.setText("ESTOQUE:");

        txtProductStock.setMaximumSize(new java.awt.Dimension(64, 22));

        lblUnit.setText("Unidades.");

        lblPurchasePrice.setText("PREÇO DE CUSTO:");

        txtPurchasePrice.setMaximumSize(new java.awt.Dimension(64, 22));

        lblUnit1.setText("Reais.");

        lblSalePrice.setText("PREÇO DE CUSTO:");

        txtSalePrice.setMaximumSize(new java.awt.Dimension(64, 22));

        lblUnit2.setText("Reais.");

        btnCancelProduct.setText("CANCELAR");
        btnCancelProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelProductActionPerformed(evt);
            }
        });

        btnSaveProduct.setText("SALVAR");
        btnSaveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProductsCreateLayout = new javax.swing.GroupLayout(pnlProductsCreate);
        pnlProductsCreate.setLayout(pnlProductsCreateLayout);
        pnlProductsCreateLayout.setHorizontalGroup(
            pnlProductsCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsCreateLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlProductsCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductsCreateLayout.createSequentialGroup()
                        .addComponent(btnCancelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductsCreateLayout.createSequentialGroup()
                        .addComponent(txtSalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUnit2))
                    .addComponent(lblSalePrice)
                    .addGroup(pnlProductsCreateLayout.createSequentialGroup()
                        .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUnit1))
                    .addComponent(lblPurchasePrice)
                    .addComponent(lblProductStock)
                    .addComponent(lblProductName)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlProductsCreateLayout.createSequentialGroup()
                        .addComponent(txtProductStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUnit)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        pnlProductsCreateLayout.setVerticalGroup(
            pnlProductsCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsCreateLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblProductName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductsCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit))
                .addGap(26, 26, 26)
                .addComponent(lblPurchasePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductsCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductsCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit2))
                .addGap(27, 27, 27)
                .addGroup(pnlProductsCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        tpProducts.addTab("Produtos", pnlProductsCreate);

        lblServiceType.setText("TIPO DE SERVIÇO:");

        txtServiceType.setMaximumSize(new java.awt.Dimension(64, 22));

        lblServicePrice.setText("PREÇO DO SERVIÇO:");

        txtServicePrice.setMaximumSize(new java.awt.Dimension(64, 22));

        lblUnit3.setText("Reais.");

        btnCancelService.setText("CANCELAR");
        btnCancelService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelServiceActionPerformed(evt);
            }
        });

        btnSaveService.setText("SALVAR");
        btnSaveService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlServicesCreateLayout = new javax.swing.GroupLayout(pnlServicesCreate);
        pnlServicesCreate.setLayout(pnlServicesCreateLayout);
        pnlServicesCreateLayout.setHorizontalGroup(
            pnlServicesCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicesCreateLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlServicesCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServicesCreateLayout.createSequentialGroup()
                        .addComponent(btnCancelService, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveService, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlServicesCreateLayout.createSequentialGroup()
                        .addComponent(txtServicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUnit3))
                    .addComponent(lblServicePrice)
                    .addComponent(txtServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceType))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        pnlServicesCreateLayout.setVerticalGroup(
            pnlServicesCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicesCreateLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblServiceType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblServicePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServicesCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(pnlServicesCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelService, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveService, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        tpProducts.addTab("Serviços", pnlServicesCreate);

        lblStableType.setText("TIPO DE ESTADIA:");

        txtStableType.setMaximumSize(new java.awt.Dimension(64, 22));

        lblStablePrice.setText("PREÇO DA ESTADIA:");

        txtStablePrice.setMaximumSize(new java.awt.Dimension(64, 22));

        lblUnit4.setText("Reais.");

        btnCancelStable.setText("CANCELAR");
        btnCancelStable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelStableActionPerformed(evt);
            }
        });

        btnSaveStable.setText("SALVAR");
        btnSaveStable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStableTypeCreateLayout = new javax.swing.GroupLayout(pnlStableTypeCreate);
        pnlStableTypeCreate.setLayout(pnlStableTypeCreateLayout);
        pnlStableTypeCreateLayout.setHorizontalGroup(
            pnlStableTypeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStableTypeCreateLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlStableTypeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStableTypeCreateLayout.createSequentialGroup()
                        .addComponent(btnCancelStable, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveStable, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStableTypeCreateLayout.createSequentialGroup()
                        .addComponent(txtStablePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUnit4))
                    .addComponent(lblStablePrice)
                    .addComponent(txtStableType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStableType))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        pnlStableTypeCreateLayout.setVerticalGroup(
            pnlStableTypeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStableTypeCreateLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblStableType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStableType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStablePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStableTypeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStablePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(pnlStableTypeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelStable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveStable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        tpProducts.addTab("Hospedagens", pnlStableTypeCreate);

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpProducts)
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpProducts)
        );

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelProductActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelProductActionPerformed

    private void btnSaveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProductActionPerformed
        JOptionPane.showMessageDialog(null, "Código de registro: #{CODE}", "Cadastro Realizado", JOptionPane.INFORMATION_MESSAGE, null);
        dispose();
    }//GEN-LAST:event_btnSaveProductActionPerformed

    private void btnCancelServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelServiceActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelServiceActionPerformed

    private void btnSaveServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveServiceActionPerformed
        JOptionPane.showMessageDialog(null, "Código de registro: #{CODE}", "Cadastro Realizado", JOptionPane.INFORMATION_MESSAGE, null);
        dispose();
    }//GEN-LAST:event_btnSaveServiceActionPerformed

    private void btnCancelStableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelStableActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelStableActionPerformed

    private void btnSaveStableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStableActionPerformed
        JOptionPane.showMessageDialog(null, "Código de registro: #{CODE}", "Cadastro Realizado", JOptionPane.INFORMATION_MESSAGE, null);
        dispose();
    }//GEN-LAST:event_btnSaveStableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelProduct;
    private javax.swing.JButton btnCancelService;
    private javax.swing.JButton btnCancelStable;
    private javax.swing.JButton btnSaveProduct;
    private javax.swing.JButton btnSaveService;
    private javax.swing.JButton btnSaveStable;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductStock;
    private javax.swing.JLabel lblPurchasePrice;
    private javax.swing.JLabel lblSalePrice;
    private javax.swing.JLabel lblServicePrice;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JLabel lblStablePrice;
    private javax.swing.JLabel lblStableType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JLabel lblUnit1;
    private javax.swing.JLabel lblUnit2;
    private javax.swing.JLabel lblUnit3;
    private javax.swing.JLabel lblUnit4;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlProductsCreate;
    private javax.swing.JPanel pnlServicesCreate;
    private javax.swing.JPanel pnlStableTypeCreate;
    private javax.swing.JTabbedPane tpProducts;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductStock;
    private javax.swing.JTextField txtPurchasePrice;
    private javax.swing.JTextField txtSalePrice;
    private javax.swing.JTextField txtServicePrice;
    private javax.swing.JTextField txtServiceType;
    private javax.swing.JTextField txtStablePrice;
    private javax.swing.JTextField txtStableType;
    // End of variables declaration//GEN-END:variables
}
